# Generated by Django 4.2.9 on 2024-02-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('adhar_number', models.CharField(max_length=12)),
                ('registration_date', models.DateField()),
                ('mobile_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='React',
        ),
    ]
